### ISSUE TITLE
Populate Emotion Labels

### ISSUE THREAD

**Issue by sublime09** [sublime09/CrySmile#5]
Labels for Happy, Sad, Angry, etc... for each tweet based off of textual analysis
Labels are numeric for each emotion.  Can be very mixed-emotion in tweets

**Comment by nuoma** [comment]
@jmpu Like what you've done previously with the election night data, can you try to get the emotions for our data? thanks

**Comment by jmpu** [comment]
@nuoma I've collected new matrices of some emojis, gonna upload them right away.

**Comment by sublime09** [comment]
Larger issue: LDAvis does not support the labeling of original docs (tweets) with the topic groups it found.
